### ISSUE TITLE
Ruby integration

### ISSUE THREAD

**Issue by manutero** [spadgos/sublime-jsdocs#238]
Would love to see **Ruby** support come to this awesome plugin.

A very basic behaviour wold be insert `#` if you are alredy in a comment block

```
# this is a comment, I would like to enter a new comment-line when enter
# <=== this
```

In a super-cool extension a function template system (as in java)

```
# [Explain the function]
# 
# More detailed description
#
# === Arguments
# 
# - a [type] [description]
# - b [type] [description]
#
# === Example
# [your example here]
#
def foo(a, b)
  :)
end
```

**Comment by 20Tauri** [comment]
I currently develop an alternative to DocBlockr called DoxyDoxygen
This language is supported.
See [Compare Doxygen to DocBlockr](https://github.com/20Tauri/DoxyDoxygen/blob/master/COMPARE.md) for details
Perhaps you may try it.
I am interested by any feedback
