### ISSUE TITLE
Support ES6 concise methods

### ISSUE THREAD

**Issue by Daniel15** [spadgos/sublime-jsdocs#283]
Given this JavaScript:
```
var Example = {
  foo(bar, baz) {
    // ...
  }
}
```

When I add a docblock above `foo(bar, baz)`, it should prefill them, similar to how it is already done for "regular" functions:
```
  /**
   * [description]
   * @param  {[type]} bar
   * @param  {[type]} baz
   * @return {[type]}
   */
```

Semantically, `foo(bar, baz) {` is exactly the same as `foo: function(bar, baz) {` and libraries like JSTransform and Traceur support transpiling it.

**Comment by Meesayen** [comment]
+ 1

**Comment by spadgos** [comment]
This was done 6 months ago. dce47831ea1be9547331e578922a6780d150fa3c

**Comment by matthiasg** [comment]
this is still not working for me at least .. 

```

class Foo {
  constructor(){
  }
  /** <TAB HERE> 
  test(a,b){
  }
```

creates

```
class Foo {
  constructor(){
  }
  /**
   * @param  {[type]}
   * @param  {[type]}
   * @return {[type]}
   */
  test(a,b){
  }
```
