### ISSUE TITLE
Change `Base File.sublime-settings` to `DocBlockr.sublime-settings`

### ISSUE THREAD

**Issue by gerardroche** [spadgos/sublime-jsdocs#313]

**Comment by rjp2525** [comment]
+1 for this issue, however @fanhexin's PR did not seem to work for me.

**Comment by spadgos** [comment]
am not!

**Comment by gerardroche** [comment]
:) I'm still here too. I just haven't had time to maybe resolve this.

**Comment by gerardroche** [comment]
This is much more complicated that I anticipated. 

There are several issues with `Base File.sublime-settings`.

- The space in the file name is an issue on some systems, which is one of the reasons some users are reporting that they can't configure DocBlockr or that the defaults are not loaded.
- DocBlockr is loading the settings indirectly, but this only works by conincidence. DocBlockr is accessing settings via `view.settings().get('key')` and ST is loading the settings file named `Base File.sublime-settings` and merging it to the view settings. For example:

    ```
    settings = sublime.load_settings('DocBlockr')
    tab_size = settings.get('tab_size') # None
    docblockr_specific_setting = settings.get('xyz') # Yes

    settings = view.settings()
    tab_size = settings.get('tab_size') # Yes
    docblockr_specific_setting = settings.get('xyz') # No, unless:
       # the settings file is named:
       # - Base File.sublime-settings
       # - Preferences.sublime-settings
       # - some other file with the same base name as some other plugin that get loaded via sublime.load_settings(). I suspect either ST itself or some other plugin is loading `Base File.sublime-settings`
    ``` 
- DocBlockr mixes access of DocBlockr specific settings and Preferences e.g. rulers, tab_size. Which is why the fix submitted by @fanhexin will unknowingly break things in subtle ways. It also introduces a distinct possibility that other bugs will be introduced by mistake later.

### Solutions

I think the configuration need to be refactored. I'm thinking something along the lines of https://github.com/gerardroche/sublime-phpunit/blob/014a11b118b0b06f39458ea498844cc47aed963f/plugin.py#L18 where a config object acts as mediator between view settings (preferences) and docblockr configurations.

**Comment by gerardroche** [comment]
I've tried many different methods to solve this.

The most straight forward solution is to rename `Base File.sublime-settings` to `Preferences.sublime-settings` and require the user to put DocBlockr settings in their `User/Preferences.sublime-settings` file. I don't see an issue with this myself. I can implement a bc fix that checks for `User/Base File.sublime-settings` on startup and moves any DocBlockr settings to `User/Preferences.sublime-settings`. From a user point of view nothing will break. In future, instead of putting settings in `User/Base File.sublime-settings` they will put them in `User/Preferences.sublime-settings`.  

if the above is ok I will do it.

The long explaination:

DockBlockr uses settings in the `Default.sublime-keymaps` to enable/disable certain keymap behaviours, which means the settings need to be loaded when ST starts. Changing `Base File.sublime-settings` to `DocBlockr.sublime-settings` and loading those settings when the plugin loads won't work, because those settings won't be available to the keymaps. The `Base File` settings *are* loaded by ST on start, though there are several reported issues where it isn't loaded properly. The `Preferences.sublime-settings` *is* loaded by ST on start and *are* available to the keymaps. 

to use a settings file like `DocBlockr.sublime-settings` the DocBlockr commands would need to be refactored to implement the `is_enabled()` command method where it would check if a setting is  enabled or disabled. The settings would then be removed from the keymaps files. I think this is crazy.

I'm not sure when plugins started to feel it necessary to have its own "named" settings file. The only benefit from it seems to be that settings don't need a prefix because they're not merged into the user's settings . But `Preferences.sublime-settings` is a)  auto loaded, so no need for plugin boilerplate code to load settings, b) the settings are available before the plugin is loaded so keymaps can use those settings and c) per-project settings work out-of-the-box.
