### ISSUE TITLE
Please add c# support

### ISSUE THREAD

**Issue by fishg** [spadgos/sublime-jsdocs#327]
Please add c# support.Thanks.

**Comment by bsqsbylt** [comment]
Please add c# support.Thanks.

**Comment by spadgos** [comment]
Please add c# support.Thanks.

**Comment by 20Tauri** [comment]
I currently develop an alternative to DocBlockr called DoxyDoxygen
This language is supported.
See [Compare Doxygen to DocBlockr](https://github.com/20Tauri/DoxyDoxygen/blob/master/COMPARE.md) for details
Perhaps you may try it.
I am interested by any feedback

**Comment by jenlampton** [comment]
Looks like this is a dupe of https://github.com/spadgos/sublime-jsdocs/issues/220?
