### ISSUE TITLE
Allow for other contexts (css)

### ISSUE THREAD

**Issue by timkelty** [spadgos/sublime-jsdocs#33]
Namely, CSS / Sass / SCSS is what I'm wanting.

While there is acutally a cssdoc spec: http://cssdoc.net/, I don't so much care about that, as it would be nice to just have a base level of functionality you could easily extend to specified contexts.

In Textmate, I would just have a docBlock snippet that I applied to all the contexts I wanted. Best way to do that here?

**Comment by darsain** [comment]
I'm really missing basic DocBlock functionality in a lot of languages. Specifically CSS related (stylus, sass, ...)

I'd really appreciate if I could set an array of contexts in which DocBlock should run in the basic form. Which is...

When I press enter here:

```
/**|
```

Create a DocBlock:

```
/**
 * |
 */
```

And when I press enter in the DocBlock above, add a new line with `[space]*[space]` before the cursor:

```
/**
 * 
 * |
 */
```

I don't want to install another package that does the exact same thing just in other contexts, and with possible small differences that would drive me insane.

Please? :)

**Comment by Aratramba** [comment]
+1 @darsain, couldn't agree more.

**Comment by benfrain** [comment]
:+1: Yes, this would be great. Love DocBlockr and I'd love to get the default behaviour in style sheets too.

**Comment by spadgos** [comment]
This basic behaviour works already.

**Comment by benfrain** [comment]
Just to add, since @spadgos comment I tried disabling Emmet and as soon as you do that, DocBlockr works as you wish in CSS/Sass

**Comment by benfrain** [comment]
One further update. If using Emmet alongside DocBlockr if you type `/**` and then <kbd>Enter</kbd> in CSS/Sass then you get a working comment block ;)

**Comment by cloud-walker** [comment]
Stylus still not supported?

**Comment by spadgos** [comment]
Pull requests still welcome :)

**Comment by darsain** [comment]
These 3 functions enabled globally in any context is all we need:

![](http://spadgos.github.io/sublime-jsdocs/images/basic.gif) ![](http://spadgos.github.io/sublime-jsdocs/images/auto-indent.gif) ![](http://spadgos.github.io/sublime-jsdocs/images/single-line.gif)

I don't see any possible issues, but if there are, a simple option would solve this:

```
docblock: true, // runs everywhere
docblock: ['css', 'scss', 'styl'], // runs in specific contexts
```

This has to be trivial to implement. You already have all the stuff working, just a little restructuring to enable it for different contexts.

I would submit a PR, but I don't do Python, and I really don't want to spend a considerable amount of time learning it just so I can copy & paste with confidence.

**Comment by jlmakes** [comment]
@darsain I have no Python skills either—but looking through the python, I don’t even see where the CSS and SCSS support comes from, let alone how to add Stylus support.
