### ISSUE TITLE
Javascript inline function blocking stopped working in 2.13.0

### ISSUE THREAD

**Issue by rgeraldporter** [spadgos/sublime-jsdocs#340]
Hi,

Javacsript inline functions have stopped working with the latest release. One abnormality in the project I'm seeing this in is that the file is a php file (.php) but contains mostly Javascript. It worked fine before, however, when I set the language in Sublime to JS as I generally do for this.

One that was generated before the changes:

    /**
     * Route to the Scan QR panel.
     * @param  {Ext.Button} btn
     * @param  {event} e
     * @param  {[type]} eOpts
     * @return {[type]}
     */
    scanQrPanel:            function( btn, e, eOpts ) {

What I get now if I try to do this again:

    /**
     * [scanQrPanel description]
     * @type {[type]}
     */
    scanQrPanel:            function( btn, e, eOpts ) {

This is on v2.13.0, OS X 10.10.1, Sublime Text 3; build 3065.

Thanks
Rob

**Comment by timothypage** [comment]
I was seeing this problem too, a quick restart of sublime text seemed to fix it

**Comment by rgeraldporter** [comment]
Yeah, this issue didn't initially go away with a restart... but has been resolved now. I wonder if another plugin was conflicting.
