### ISSUE TITLE
Disable templates when opening a doc comment

### ISSUE THREAD

**Issue by axel22** [spadgos/sublime-jsdocs#348]
Please add an option to disable adding a template when a doc comment is opened.

For example:

    /**|
    def ...

After hitting space:

    /** @type {[type]} [description] */
    def ...

This is not very useful for me, and I would really like to disable it, as I have to delete it each time.

**Comment by spadgos** [comment]
Add `jsdocs_quick_open_inline: false` to your settings now to disable that.
