### ISSUE TITLE
Sublime Text 3, Javascript - Function definition not fully fleshed out

### ISSUE THREAD

**Issue by gojohnnygo** [spadgos/sublime-jsdocs#349]
Looks like it's not importing the parameters and description. See image below. 

![screen shot 2015-02-17 at 5 25 14 pm](https://cloud.githubusercontent.com/assets/197015/6240985/176aa052-b6cb-11e4-99f2-b1b4fc287bfe.png)

**Comment by dmarg** [comment]
I am having this same situation happen. Should it be importing the parameter names?

**Comment by dmarg** [comment]
@gojohnnygo I was having a similar issue and then I restarted my Sublime Text 3 and it is now working. Have you tried to restart your Sublime Text 3?

**Comment by gojohnnygo** [comment]
@dmarg I thought I did. I just restarted my computer and it worked. Thanks!
