### ISSUE TITLE
JS: function names are not substituted

### ISSUE THREAD

**Issue by strelga** [spadgos/sublime-jsdocs#362]
I use SublimeText3 on MacOS X Yosemite with your packge (used it on Linux and it was awesome) and it seems that something works not the way I expected. E.g. `//`+`Enter` does not substitute `//` to the next line. And when I use block comments `/**`+`Enter` before the function, it substitutes everything except the function arguments' names:
```
/**
 * [object2hash description]
 * @param  {[type]}
 * @param  {[type]}
 * @param  {[type]}
 * @return {[type]}
 */
var object2hash = function (obj, salt, needConvert) {
```
What could it be? Maybe I'm missing some other packages or the settings of DocBlockr are incorrect?

**Comment by spadgos** [comment]
Seems the same as #334. It appears that for some people, the default setting doesn't appear to merge in properly. The solution there was to copy the appropriate settings into your User preferences.
