### ISSUE TITLE
Does not work when assigning function to a name

### ISSUE THREAD

**Issue by nagarjun** [spadgos/sublime-jsdocs#379]
In frameworks like Ember or Sails.js, I have to declare functions like this:

    doSomething: function(a, b) {
        return true;
    }

In these situations, DocBlocker picks up that there is a function with two arguments but does not pick up argument and function names. Am I missing some configuration setting?

**Comment by spadgos** [comment]
That example works for me...
![selection_115](https://cloud.githubusercontent.com/assets/426222/8403386/66c25286-1e44-11e5-8e21-d56df5b4e453.png)

Do you have your syntax highlighting set to Javascript?

**Comment by nagarjun** [comment]
@spadgos It seems to work now. :-) That was odd. I think I just had to restart Sublime. I'm sorry about that.
