### ISSUE TITLE
Reparse comment block changes indentation

### ISSUE THREAD

**Issue by ssteinerx** [spadgos/sublime-jsdocs#383]
When a comment block is first created with /**<tab>, indentation is like this.
```
/**
 *
 *
 **/
```
I.E. the leading asterisks are lined up.

When you reparse the comment block, the alignment changes to this:
```
/**
*
*
**/
```
I.E. the leading astericks now line up under the leading slash.

I'd like it to just leave it the way it was and drop me back into being able to tab from field to field.

**Comment by spadgos** [comment]
Ah, this was fixed in 09fabd06a4e4cff2401d3f33603f5965062828f4 but I forgot to deploy it >_<

Comin' right up...

**Comment by ssteinerx** [comment]
Thanks!

Steve
