### ISSUE TITLE
Can't write @ inside the docblocker.

### ISSUE THREAD

**Issue by erdemkeren** [spadgos/sublime-jsdocs#390]
After installing DocBlockr to Sublime Text 3,

When I try to add @ [at] sign inside a docblock, it prevents the default functionality of my keyboard and instead, removes white spaces and empty lines inside the docBlock.

My keyboard layout is 'Turkish Q' and by default, '[AltGr] + Q' types an @ [at] sign.

**Comment by spadgos** [comment]
Okay cool... Could you open the console (`View -> Show Console`) and run `sublime.log_commands(True)` and then repro the error. It should show what's actually running.

**Comment by erdemkeren** [comment]
command: drag_select {"event": {"button": 1, "x": 117.17578125, "y": 94.640625}} (click on doc block line)
command: jsdocs_wrap_lines (AltGr + Q)

**Comment by spadgos** [comment]
Ah haa, it's a conflict in the key map then. I actually don't know how to go about fixing this. If the keypress is coming through as alt+q, then that's all I can really work with. A workaround for you might be to copy the [`@` keyhandlers](https://github.com/spadgos/sublime-jsdocs/blob/5eb8e09204190baa75e9a853dd45282e7b8e7a81/Default.sublime-keymap#L174-L190) into your own keymap file and change the keys to be Alt Q

**Comment by 20Tauri** [comment]
I have to press Ctrl+Alt+Q or AltGr+Q to have a @.
Are you using OS/X operating system ?
If yes, this is probably the common key binding that cause problem...

**Comment by erdemkeren** [comment]
Whoops, I typed it wrong. I think I have never looked to the keyboard when typing '@'. Yes we have the @ sign positioned at the bottom right of the Q key (talking physically) on a Turkish Q keyboard (for PC, it is also AltGr + Q on both Win and Linux). And ⌘ + Q means quit. Sorry that was a huge mistake. 

However when I type AltGr + Q (the key combination to print @) I can't have the @ sign and instead jsdocs_wrap_lines runs.

**Comment by spadgos** [comment]
Did you try the workaround? (using alt+q instead of cmd+q...)

**Comment by erdemkeren** [comment]
Let me explain. 
I think I was dreamy a little bit yesterday and That is why I wrote Cmd+Q instead of Alt+Q. That was a mistake. Sorry about that. 
To be better clear; 
In my keyboard layout I use Alt + Q and AltGr + Q to type an @ sign. (double checked :smile:). However, after installing DocBlockr it overrides Alt + Q (the right side one); however It is common to use Right Side Alt + Q to write an @ sign, I don't want that and I can not change that. That was my problem and I thought that was a mistake.

Now I see that this is a feature and not a mistake. However I don't want the package to override my alt + Q. How can I do that?

**Comment by spadgos** [comment]
I'm suggesting that you re-override it in your own User.sublime-keymap. Copy the block from DocBlockr's keymap which deals with "@" (linked above), and then replace the "@" with "Alt-Q".

**Comment by erdemkeren** [comment]
Thanks, that worked.
