### ISSUE TITLE
Is there an option to have [description] start on a new line with indentation?

### ISSUE THREAD

**Issue by kruncher** [spadgos/sublime-jsdocs#405]
For instance:

``` javascript
/**
 * [foo description]
 *
 * @param {[type]} a
 *   [description]
 * @param {[type]} b
 *   [description]
 * @returns {[type]}
 *   [description]
 */
function foo(a, b) {
}
```

**Comment by spadgos** [comment]
There isn't that option.

**Comment by 20Tauri** [comment]
I currently develop an alternative to DocBlockr.
I've receive a similar request ( https://github.com/20Tauri/DoxyDoxygen/issues/23 ).
I've added an option for the Doxygen commands...
JsDoc3 is supported... If there's a need, I may extend this option to JsDoc in the next release

**Comment by kruncher** [comment]
@20Tauri It would sure be great if you could extend the option to JsDoc in your next release. I adjusted my formatting convention a while back when I found that the Drupal developers were doing this in their source base. I rather like it because it avoids all the column alignment nonsense.

**Comment by 20Tauri** [comment]
This option is already released in the "Doxygen (evolution)" branch...
Thanks, Drupal is a good reference (I'll use it as example in documentation: "\n  ").
