### ISSUE TITLE
For nodejs module function define

### ISSUE THREAD

**Issue by godblesshugh** [spadgos/sublime-jsdocs#411]
this is my code:
`AV.Cloud.define("this is function name", function(req, res){var param = req.params.param; res.success(true);}`
but the autocomplete tag "@param" always output this:
@param    {[type]}        req        [description]
@param    {[type]}        res){ var param         [description]
Is there any solution for that? or any way i can somehow just delete param in settings and put 
"@param {${1:[type]}} ${1:[name]} ${1:[description]}" in jsdocs_extra_tags

**Comment by spadgos** [comment]
It's a little strange to be using JSDoc to document that, since it's not actually a method that you're exposing anywhere, but anyway, yeah the plugin should be able to do a better job of it.

**Comment by godblesshugh** [comment]
Yes, that's actually a interface for our app, not for open using.
So, any idea can this using more easily?

**Comment by godblesshugh** [comment]
Maybe, for some cases not like a method, default params will be more convenient：
/**
- [description]
- @function [function_name]
- @param    {[type]} [varname] [description]
- @param    {[type]} [varname] [description]
- @returns  {[type]} [description]
  */

**Comment by spadgos** [comment]
That seems like it'd be incorrect more often than not.

**Comment by godblesshugh** [comment]
seem so, anyway, thanks for this awesome plugin
