### ISSUE TITLE
Setting to put @param [desc] on the following line (doxygen standard)

### ISSUE THREAD

**Issue by jenlampton** [spadgos/sublime-jsdocs#419]
We use doxygen standards for docblocks in PHP, and would like the [desc] to appear on the line following the @param line, instead of at the end of the line, like so:

```
/**
 * Menu callback to export a table as a CSV.
 *
 * @param string $entity_type
 *   The type of entity, e.g. node.
 * @param string $entity_id
 *   The id of the entity.
 * @param string $field_name
 *   The machine name of the field to load.
 * @param string $langcode
 *   The language code specified.
 * @param string $delta
 *   The field delta to load.
 */
```

Would it be possible to add a setting for this as well?

**Comment by spadgos** [comment]
Don't mean to sound condescending, but my suggestion is to press Enter.

**Comment by jenlampton** [comment]
> Don't mean to sound condescending

It might not have sounded condescending if you didn't write that... but now it does. :(

**Comment by spadgos** [comment]
Sorry :( honestly didn't want to make anyone feel bad.
