### ISSUE TITLE
I never got it working for any language, what to do?

### ISSUE THREAD

**Issue by evandrocoan** [spadgos/sublime-jsdocs#421]
![issyncedsidebarenabled](https://cloud.githubusercontent.com/assets/5332158/18531553/4071a278-7aad-11e6-9701-abb5f951d04d.gif)

I am using the default settings, and the plugin is running without errors.

My installed packages: https://github.com/evandrocoan/SublimeTextStudio/blob/master/User/Package%20Control.sublime-settings

Sublime Text version 3114 - Windows 10

**Comment by spadgos** [comment]
Can you open the console (Ctrl + `) and type `sublime.LogCommands(True)` and show the output when pressing enter? My suspicion is that the plugin isn't actually being activated. What's the language you're using there? These are the languages supported: https://github.com/spadgos/sublime-jsdocs/blob/master/jsdocs.py#L58-L72

**Comment by evandrocoan** [comment]
Do you mean `sublime.log_input(True); sublime.log_commands(True); sublime.log_result_regex(True)`: 
https://github.com/evandrocoan/SublimeTextStudio#debugging

Output:

```
>>> sublime.log_input(True); sublime.log_commands(True); sublime.log_result_regex(True)
key evt: keypad_divide
chr evt: / (0x2f)
key evt: keypad_multiply
chr evt: * (0x2a)
key evt: keypad_multiply
chr evt: * (0x2a)
key evt: enter
command: insert {"characters": "\n"}
```

Its is C++.
![image](https://cloud.githubusercontent.com/assets/5332158/18587665/7b0bee78-7bf9-11e6-9aeb-73273532bb82.png)

**Comment by spadgos** [comment]
Ooh, didn't even know about those other ones.

Anyway, yeah the line `command: insert {"characters": "\n"}` shows that DocBlockr isn't being invoked. [This is the key combo](https://github.com/spadgos/sublime-jsdocs/blob/master/Default.sublime-keymap#L3-L10) which should be triggering it:

``` json
  { "keys": ["enter"], "command": "jsdocs",
    "context": [
      { "key": "setting.auto_indent",   "operator": "equal",          "operand": true,                        "match_all": true },
      { "key": "selection_empty",       "operator": "equal",          "operand": true,                        "match_all": true },
      { "key": "auto_complete_visible", "operator": "equal",          "operand": false,                       "match_all": true },
      { "key": "preceding_text",        "operator": "regex_contains", "operand": "^\\s*(\\/\\*|###)[*!]\\s*$", "match_all": true }
    ]
  },
```

Is it possible that you have auto_indent set to false?

**Comment by evandrocoan** [comment]
> Is it possible that you have auto_indent set to false?

No, these are my `auto_settings`:

``` json
    "autoIndent": true,
    "auto_complete": true,
    "auto_complete_cycle": true,
    "auto_complete_delay": 350,
    "auto_complete_with_fields": true,
    "auto_indent": true,
    "auto_match_enabled": false,
```

I got this on my console, after delete most of my key settings:

```
key evt: keypad_divide
chr evt: / (0x2f)
key evt: keypad_multiply
chr evt: * (0x2a)
key evt: keypad_multiply
chr evt: * (0x2a)
key evt: enter
command: jsdocs
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\DocBlockr\jsdocs.py", line 154, in run
    self.initialize(self.view, inline)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\DocBlockr\jsdocs.py", line 188, in initialize
    self.parser = parser = getParser(v)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\DocBlockr\jsdocs.py", line 57, in getParser
    print( 'getParser: ' + scope + res + sourceLang + viewSettings )
TypeError: Can't convert '_sre.SRE_Match' object to str implicitly
```

This is my full `User.sublime-keymap` file: https://gist.github.com/evandrocoan/80c7f077201e5368e026d31b4c62d8c6

**Comment by spadgos** [comment]
The stack trace there shows some line numbers and code which don't align with the current version of DocBlockr. Are you up to date? If you open the jsdocs.py file (path is in your stack trace) the version at the top should read 2.13.3.

**Comment by gerardroche** [comment]
Note: your auto indent setting: `"autoIndent": true` should be `"auto_indent": true`.

**Comment by evandrocoan** [comment]
It says: `DocBlockr v2.14.1`. 

I attacked the package I am using: [DocBlockr.zip](https://github.com/spadgos/sublime-jsdocs/files/486337/DocBlockr.zip)

They still coming:

```
>>> 
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\DocBlockr\jsdocs.py", line 154, in run
    self.initialize(self.view, inline)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\DocBlockr\jsdocs.py", line 188, in initialize
    self.parser = parser = getParser(v)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\DocBlockr\jsdocs.py", line 57, in getParser
    print( 'getParser: ' + scope + res + sourceLang + viewSettings )
TypeError: Can't convert '_sre.SRE_Match' object to str implicitly
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\DocBlockr\jsdocs.py", line 154, in run
    self.initialize(self.view, inline)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\DocBlockr\jsdocs.py", line 188, in initialize
    self.parser = parser = getParser(v)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\DocBlockr\jsdocs.py", line 57, in getParser
    print( 'getParser: ' + scope + res + sourceLang + viewSettings )
TypeError: Can't convert '_sre.SRE_Match' object to str implicitly
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\DocBlockr\jsdocs.py", line 154, in run
    self.initialize(self.view, inline)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\DocBlockr\jsdocs.py", line 188, in initialize
    self.parser = parser = getParser(v)
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\DocBlockr\jsdocs.py", line 57, in getParser
    print( 'getParser: ' + scope + res + sourceLang + viewSettings )
TypeError: Can't convert '_sre.SRE_Match' object to str implicitly
```

**Comment by spadgos** [comment]
Wow, i dunno where I got 2.13.3 from... weird.

In that stack trace it shows this line of code:

``` py
print( 'getParser: ' + scope + res + sourceLang + viewSettings )
```

however I don't see that in my source anywhere. Do you know where it came from? It looks like it might be the source of the bug, since it's trying to convert something to a string to print it.

**Comment by evandrocoan** [comment]
Yeah, that is it. Why there is a print on the final code? Just apply the `str( )` operator to it.

```
print( 'getParser: ' + str( scope ) + str( res ) + str( sourceLang ) + str( viewSettings ) )
```

**Comment by gerardroche** [comment]
I can't find that print statement anywhere is the repository at all.

**Comment by evandrocoan** [comment]
Sorry, I found it on my repository. I putted it there a long time ago. Now It is almost working.

When I do `/*` and press enter it does this:

![multiselection_jumps](https://cloud.githubusercontent.com/assets/5332158/18767702/2bf90f5c-80f7-11e6-95c8-4cf466e60719.gif)

But was supposed to the next line be like this and do to create more endings `*/` when back again to the first line and pressed enter:

```
/*
 * |
 */
```

And when pressed enter on the second line, it should be like this:

![multiselection_jumps](https://cloud.githubusercontent.com/assets/5332158/18768579/c3ef0be0-80fc-11e6-909c-fd9e5be0d3cd.gif)

Now when I do `/**` and press enter, it does nothing. The debugging output is:

```
key evt: keypad_divide
chr evt: / (0x2f)
key evt: keypad_multiply
chr evt: * (0x2a)
key evt: keypad_multiply
chr evt: * (0x2a)
key evt: enter
command: jsdocs
key evt: enter
command: jsdocs
key evt: enter
command: jsdocs
key evt: enter
command: jsdocs
key evt: enter
command: jsdocs
key evt: enter
command: jsdocs
key evt: enter
command: jsdocs
key evt: enter
command: jsdocs
key evt: enter
command: jsdocs
key evt: enter
command: jsdocs
key evt: enter
command: jsdocs
```

**Comment by spadgos** [comment]
The leading asterisk is only added to subsequent lines when you open the block with `/**`. It does look a little buggy that it keeps adding `*/` closing marks, but it's not entirely unexpected.

For example:

``` js
/*
foo
bar
baz
*/
```

If you press enter after the opening `/*` you'd expect it to _not_ add the closer, right? But what about this code?

``` js
/*
foo
bar
/*
baz
*/
```

**Comment by evandrocoan** [comment]
Ok them, now there is only one problem. (it neither add a new line).

> Now when I do /*\* and press enter, it does nothing. The debugging output is:
> 
> ```
> key evt: keypad_divide
> chr evt: / (0x2f)
> key evt: keypad_multiply
> chr evt: * (0x2a)
> key evt: keypad_multiply
> chr evt: * (0x2a)
> key evt: enter
> command: jsdocs
> key evt: enter
> command: jsdocs
> key evt: enter
> command: jsdocs
> key evt: enter
> command: jsdocs
> key evt: enter
> command: jsdocs
> key evt: enter
> command: jsdocs
> key evt: enter
> command: jsdocs
> key evt: enter
> command: jsdocs
> key evt: enter
> command: jsdocs
> key evt: enter
> command: jsdocs
> key evt: enter
> command: jsdocs
> ```

**Comment by evandrocoan** [comment]
I just tried again and it worked 👍 

![ezgif-1908081531](https://cloud.githubusercontent.com/assets/5332158/18835599/317050c0-83d2-11e6-8c16-8f446406631e.gif)

What I did, from yesterday until today I reinstalled `Sublime Text` several times.
