### ISSUE TITLE
@example turning into @apiExample

### ISSUE THREAD

**Issue by maikelmclauflin** [spadgos/sublime-jsdocs#425]
name says it all. what gives? am i missing a setting somewhere?

**Comment by gerardroche** [comment]
Which language? Can you show more details, a specific example might help, because I can't reproduce it.

**Comment by maikelmclauflin** [comment]
sorry, this was an error on my end. i installed 2 snippet packages at the same time unfortunately that other (crappier looking) one kept winning out. thanks for your response though

**Comment by gerardroche** [comment]
:) no worries. Please close the issue.
