### ISSUE TITLE
ToolTips in Code

### ISSUE THREAD

**Issue by chrom007** [spadgos/sublime-jsdocs#436]
How to use this Docs in SublimeText as ToolTips Help in code for my functions? 
Example (non ST): 

![tmswg](https://cloud.githubusercontent.com/assets/12010456/23977140/16d739d2-09f5-11e7-87b1-3e5a89d9758b.png)

**Comment by spadgos** [comment]
That's not really feasible without having a proper parser which can understand the dependencies, imports and so on. Out of scope for DocBlockr, sorry.
