### ISSUE TITLE
alternative/similar projects?

### ISSUE THREAD

**Issue by pixelass** [spadgos/sublime-jsdocs#450]
I've been using DocBlockr for a long time but the Owner declared it as "Not under active development" (#430) and does not seem to look at issues and Pull requests anymore (just my guess from what I read in the issues and PRs)
I fully understand if someone does not have enough time to support repos anymore. No offence.

**Here's my question**: Does anybody know any alternatives to this sublime plugin?

Maybe @spadgos can add a note to the Readme.md that mentions the status of this project #430 #445 
@spadgos Thanks so much for this amazing plugin. It would be sad if it eventually died due to neglection.

**Comment by gerardroche** [comment]
I'm looking to become a maintainer: https://github.com/spadgos/sublime-jsdocs/issues/445. I've contributed a bit in the past and can handle basic stuff dealing with PRs.

I'll fork the project soon if there's no updates in the near future or becoming a maintainer is a noop.

**Comment by 20Tauri** [comment]
I'm the maintainer of an alternative called [DoxyDoxygen](https://github.com/20Tauri/DoxyDoxygen).

I sometime look on similar software's forum to see the need of users. Often features are implemented and my package is not affected by common issues. An example with C++
```c++
/**
 * @brief      { function_description }
 *
 * @param      head               The head
 * @param[in]  callback_function  The callback function
 */
void foreach_data_node_callback(struct data_node **head, void (*callback_function)(struct data_node *))
```

My plugin has a smaller audience than DocBlockr. But users give me a good feedback (thanks to them !)

**Comment by pixelass** [comment]
Moving away from Github. Feel free to reopen if interested.
