### ISSUE TITLE
Allow configuration of default function prefix to assign @private 

### ISSUE THREAD

**Issue by couto** [spadgos/sublime-jsdocs#85]
At this moment, any function that starts with an underscore, is marked as `@private` by default, which is awesome.

However in Javascript there's no private/protected methods (unless you're using the module pattern),  therefore the convention to mark private/protected methods vary greatly... 
Some people even use `$` instead of `_` to do this differentiation...

So what I'm suggesting is to allow this prefix to be configured in the user options or maybe extend the `jsdocs_notation_map` to also apply to function names, this way it would be possible to add private and protected methods to the doc block, independently of the syntax used =)

**Comment by hadnet** [comment]
After 6 years, doesn't work for variables yet?
