### ISSUE TITLE
[JavaScript] @private variables

### ISSUE THREAD

**Issue by solcik** [spadgos/sublime-jsdocs#94]
When I try this notation, it will mark only functions with this prefix, but variables it will not.
Is it possible to implement it for variables?

{
"prefix": "_",
"tags": ["@Private"]
}

**Comment by zheeeng** [comment]
In 2.14.1 today, I tried this feature and met the same situation, `@private` works only on function not variable.

**Comment by jose-vasquez-mantum** [comment]
I have the same problem, this only work for function but not for var (in PHP)
